// Code generated by coz. DO NOT EDIT.
/**
 * Calendar of the-components
 * @module the-calendar
 */
'use strict'

import TheCalendar from './TheCalendar'
import TheCalendarStyle from './TheCalendarStyle'

export {
 TheCalendar,
 TheCalendarStyle,
}
